### PR TITLE
Remove this if statement

### PR DESCRIPTION
**Pull request by vbv-shm**
This if statement prevents the string "years" to come after the age. This commit removes it and the unit "year" is added with age.

### CODE REVIEW

**Comment by spencermountain** [comment]
hey Vaibhav - just getting to this - would you like me to merge this?
happy to improve this file, in any way.
cheers

**Comment by vbv-shm** [comment]
Hi Spencer, I am new and noob in the software world. 
Please verify that merging won't cause any issues.

**Comment by spencermountain** [comment]
welcome! yeah, i think the idea was that it would only print the unit if it wasn't years:
```
npx space-age june 8 1992 
// 30
npx space-age june 8 1992 --months
// 368 (months)
```
good pr! think this is intended behaviour though.
cheers

**Comment by vbv-shm** [comment]
Thank you.

**Pull request closed without merging**
