### PR TITLE
Typescript types

### PR DESCRIPTION
**Pull request by jecraig**
This adds typescript definitions for methods that are in the api docs. I'm not too familiar with this library yet (although I want to start using it), so let me know if there's any issues. This should also close https://github.com/spencermountain/spacetime/issues/4.

Here's a rough fake usage in Typescript.

```
import spacetime from 'spacetime';
import { Spacetime } from 'spacetime/types/types';

export function demo() {
	let now = new Date();
	let nowS = spacetime(now);
	let nextS = spacetime(now).add(1, 'day');
	console.log(nowS.isSame(nextS, 'week'));

	console.log(nowS.format('iso-utc'));
	const spaceNow = spacetime.now();
	console.log(spaceNow.startOf('century'));

	let millies: number = spaceNow.millisecond();
	let updated: Spacetime = spaceNow.millisecond(123123);
}
```

### CODE REVIEW

**Comment by spencermountain** [comment]
YOU ARE THE BEST
thank you!

**Comment by jecraig** [comment]
@spencermountain Will you let me know when you're getting close to the next release. I've been using the library with the types and making adjustments as I find them. But I don't want to spam you guys with PRs.

**Comment by spencermountain** [comment]
please spam me with prs!
I don't anticipate any type changes in v6, things are settling down.

I've been trying to generate types for many months now. Each time i'd read a blog post, I'd get more confused - do you know a good way to hook it into tests? The best scenario would be a `npm run test:types` - where it makes-sure the typefile is sane - is there a best-practice you'd recommend?

**Comment by jecraig** [comment]
I don't have any idea currently on how to parse the types and use that to do stuff, but I was going to look into generating the API file off the type definitions. I'll keep a look out for way of doing surface tests off the type definitions as well.

**Comment by spencermountain** [comment]
hey @jecraig how are ya doin? I took a look through your typings, and learned a lot from this. thank you again.

i put [an attempt](https://github.com/spencermountain/spacetime/tree/dev/test/types) at a `npm run test:types` - i really have no idea what i'm doing, and would love some help.

when i run it, i get `Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/Users/spencer/mountain/spacetime/types/index")' has no compatible call signatures.`

if i remove the `types` directory, it'll run fine.
any advice?

**Comment by spencermountain** [comment]
the test doesn't need to be thorough - i just know i'm gonna forget about changing the types, over time. I want something to yell at me when i do.

**Comment by jecraig** [comment]
I'll try to take a look this weekend.

**Pull request merged**
