### PR TITLE
add function to determine timezone with date border

### PR DESCRIPTION
**Pull request by MartinSpd**
Added a method `dateBorder` to `src/methods.js`:
1. gets current time (if it's in 12-hour format adds 12 hours)
2. gets current timezone offset
3. counts number of hours to the end of the day
4. timezone with new date is: offset + number of hours to the end of the day
5. logs and returns timezone with date border

### CODE REVIEW

**Comment by spencermountain** [comment]
hey Martin, thank you for your work. 
I'm a little confused - `.dateBorder()` returns the current time at the international date line? is that it?

Happy to add new functions to spacetime - what is the application you're thinking of?
maybe we can think about some ways to accomplish this

**Comment by MartinSpd** [comment]
Hi, I'm currently, doing an online course about ES6, which has also coding part and one of assignments was about participating on someone else's project. I found yours and it was interesting to me it deals with world time.
I got an idea add this simple function to find out, where on the Earth starts new day compare to your current location. I have to play with this function a bit more, because I think return complex data (as a JSON) about timezone with date border would be much better. What do you think?

**Comment by spencermountain** [comment]
Thanks, help is always welcome. Congratulations on your first pr!
great work.

this functionality is already provided I think by the `.whereIts()` function:
```js
spacetime.whereIts('11:00pm', '12:00am') 
```
something like that would return a list of timezones that are currently experiencing a new day.

**Comment by spencermountain** [comment]
I'm trying to think of a good first-bug for a pr on this library, but I can't currently think of one.

Wanna write some tests for the `whereIts` method?
cheers

**Comment by MartinSpd** [comment]
Ah, okay. I forget about this method. It can also do this trick. In my code i fixed codacy issue and i think i just forget add timezone method in return statement. Yea, sure I can play with some tests and push them, when I'm done.

**Comment by spencermountain** [comment]
thanks!

**Pull request closed without merging**
