### PR TITLE
Fix pacific/chatham iana DST change time

### PR DESCRIPTION
**Pull request by misak113**
* see https://www.zeitverschiebung.net/en/timezone/pacific--chatham

### CODE REVIEW

**Comment by spencermountain** [comment]
yikes! good find!

**Comment by spencermountain** [comment]
will try to release this as a hotfix this evening.

**Comment by misak113** [comment]
Thx. I have no relation to that Zeland islands, but very randomly, I used the timezone in my unit tests. That's a really funny accident.

**Comment by spencermountain** [comment]
released as 6.15.1
thanks!

**Pull request merged**
