### PR TITLE
Allow space before am/pm suffix

### LINKED ISSUE #238: time() should accept 12-hour times that contain a space before the am/pm suffix
Currently the `time()` setter accepts a 12-hour time in the format "6:30pm", however "6:30 pm" fails. 

```javascript
console.log(spacetime().time('6:30 pm').format('nice')) // Nov 11th, 6:30am
```

Having a space before the am/pm suffix seems fairly common, and therefore should be supported. 

Happy to create a PR for this if that is acceptable.

### PR DESCRIPTION
**Pull request by coatesap**
Fixes #238

### CODE REVIEW

**Comment by spencermountain** [comment]
beautiful! thank you Andy.

**Comment by coatesap** [comment]
Hi @spencermountain - any chance of a version bump for this?

**Comment by spencermountain** [comment]
sure - let me squeeze-in #240 - will try and do it this weekend or else monday.

**Comment by spencermountain** [comment]
released as `6.10.0` - thanks!

**Pull request merged**
