### PR TITLE
Month days amount helper

### PR DESCRIPTION
**Pull request by m1212e**
This is a small method for providing easy access to the amount of days in the month of a Spacetime. I found this useful while building my own datepicker.

### CODE REVIEW

**Comment by spencermountain** [comment]
great idea. I'll add this to the readme and do a release this week.
thank you!

**Comment by m1212e** [comment]
Sure thing. Thanks for your work!

**Comment by spencermountain** [comment]
hey @m1212e I renamed this method to `daysInMonth()` - to avoid confusion about what month you're getting.
released as `v6.16.3` - thank you!

**Comment by spencermountain** [comment]
this was really well-made.

**Pull request merged**
