### PR TITLE
Fixing a typing issue with every

### PR DESCRIPTION
**Pull request by jecraig**
Fixing https://github.com/spencermountain/spacetime/issues/197#issuecomment-644467672

### CODE REVIEW

**Comment by spencermountain** [comment]
thank you!

**Comment by adisreyaj** [comment]
@spencermountain Is this updated pushed to the npm package? 
Because it throws the error on version 6.6.0.

**Comment by spencermountain** [comment]
hey @adisreyaj yeah it's just behind another small fix. I'll try to release it today.

**Comment by spencermountain** [comment]
released as 6.6.1

**Pull request merged**
